In [50]:
#импортируем библиотеку pandas
import pandas as pd

In [51]:
#загружаем датасет
twitch_df = pd.read_csv('../data/twitch_data.csv')

In [52]:
#убеждаемся, что все правильно загрузили и заодно смотрим на часть данных в датасете
twitch_df.head()

,Channel,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
0,xQcOW,6196161750,215250,222720,27716,3246298,1734810,93036735,True,False,English
1,summit1g,6091677300,211845,310998,25610,5310163,1370184,89705964,True,False,English
2,Gaules,5644590915,515280,387315,10976,1767635,1023779,102611607,True,True,Portuguese
3,ESL_CSGO,3970318140,517740,300575,7714,3944850,703986,106546942,True,False,English
4,Tfue,3671000070,123660,285644,29602,8938903,2068424,78998587,True,False,English

In [53]:
#смотрим информацию о датасете
twitch_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Channel               1000 non-null   object
 1   Watch time(Minutes)   1000 non-null   int64
 2   Stream time(minutes)  1000 non-null   int64
 3   Peak viewers          1000 non-null   int64
 4   Average viewers       1000 non-null   int64
 5   Followers             1000 non-null   int64
 6   Followers gained      1000 non-null   int64
 7   Views gained          1000 non-null   int64
 8   Partnered             1000 non-null   bool
 9   Mature                1000 non-null   bool
 10  Language              1000 non-null   object
dtypes: bool(2), int64(7), object(2)
memory usage: 72.4+ KB

Пропущенных данных в датасете нет. Поэтому приступим к рассмотрению других признаков, кроме вещественных. Кратко говоря, задача сформулирована так, что необходимо предсказать вещественное значение по другим вещественным значениям. Поэтому необходимо избавиться от всех признаков, не имеющих вещественный тип. Задача была так сформулирована, потому что был проведен анализ по данным и было выяснено, что такие признаки, как "Partnered", "Mature", "Language", "Channel" не влияют или почти не влияют на конечный результат. "Channel", очевидно, является неинформативным признаком.

In [54]:
#удаляем столбец Channel
twitch_df = twitch_df.drop(['Channel'], axis=1)

В следующей ячейке видно, что признак "Partnered" является незначительным, поэтому его тоже можно удалить, ведь из 1000 стримеров лишь 22 не имеют партнерства с Twitch.

In [55]:
print(twitch_df[twitch_df['Partnered'] == 1].sum())
twitch_df = twitch_df.drop(['Partnered'], axis=1)

Watch time(Minutes)                                          412305426195
Stream time(minutes)                                            117775290
Peak viewers                                                     36498205
Average viewers                                                   4664724
Followers                                                       562751329
Followers gained                                                202365842
Views gained                                                  11282522709
Partnered                                                             978
Mature                                                                225
Language                EnglishEnglishPortugueseEnglishEnglishEnglishE...
dtype: object

In [56]:
print(list(twitch_df[twitch_df['Mature'] == 1].index))

[2, 10, 15, 16, 24, 32, 42, 45, 55, 63, 65, 70, 71, 74, 77, 80, 84, 89, 114, 116, 119, 120, 126, 137, 138, 140, 145, 166, 167, 168, 171, 172, 176, 179, 181, 182, 184, 190, 197, 211, 212, 216, 218, 226, 230, 231, 242, 244, 245, 248, 249, 254, 259, 270, 273, 274, 280, 286, 295, 296, 298, 300, 301, 307, 308, 315, 323, 329, 331, 339, 340, 345, 353, 361, 365, 366, 368, 369, 374, 381, 382, 387, 404, 406, 416, 417, 419, 421, 431, 434, 453, 458, 466, 467, 468, 480, 481, 484, 487, 489, 491, 495, 498, 503, 505, 508, 512, 519, 524, 526, 538, 545, 548, 551, 555, 556, 559, 568, 573, 576, 581, 583, 589, 592, 597, 606, 620, 623, 624, 633, 638, 643, 648, 653, 655, 660, 666, 670, 673, 674, 676, 677, 679, 683, 688, 693, 698, 705, 711, 715, 716, 717, 723, 727, 729, 731, 735, 742, 744, 751, 752, 760, 762, 766, 769, 771, 774, 778, 779, 783, 786, 790, 793, 796, 801, 804, 807, 808, 810, 813, 815, 816, 820, 821, 824, 826, 829, 831, 833, 834, 839, 842, 848, 849, 859, 861, 867, 868, 873, 882, 889, 891, 897, 901, 908, 909, 910, 911, 914, 922, 927, 934, 936, 939, 940, 942, 958, 960, 967, 968, 970, 971, 972, 975, 980, 983, 984, 985, 988, 993]

По данным сверху видно, что стримеры, имеющие метку 18+, распределены более-менее равномерно по всему топу, что означает, что данный признак также неинформативен.

In [57]:
twitch_df = twitch_df.drop(['Mature'], axis=1)

In [58]:
for lang in twitch_df.Language.unique():
    temp = list(twitch_df[twitch_df['Language'] == lang].index)
    print(f'{lang} : {temp}')

English : [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 19, 20, 22, 23, 27, 29, 32, 33, 35, 37, 38, 40, 41, 42, 44, 46, 47, 48, 49, 51, 52, 54, 55, 61, 62, 63, 65, 66, 67, 70, 71, 73, 74, 75, 76, 77, 79, 80, 81, 83, 86, 87, 89, 90, 93, 94, 95, 96, 99, 104, 111, 112, 113, 114, 115, 117, 118, 119, 122, 123, 128, 131, 133, 134, 135, 136, 138, 140, 142, 148, 149, 152, 153, 155, 162, 163, 165, 166, 168, 169, 172, 175, 178, 179, 181, 182, 183, 184, 186, 189, 192, 194, 196, 197, 201, 202, 203, 204, 205, 206, 207, 209, 210, 211, 212, 213, 214, 216, 218, 220, 222, 225, 228, 229, 233, 234, 235, 237, 238, 240, 243, 244, 245, 246, 250, 251, 254, 255, 258, 259, 261, 262, 263, 264, 265, 267, 268, 270, 271, 273, 274, 278, 280, 281, 283, 285, 286, 288, 289, 290, 292, 293, 294, 296, 300, 301, 302, 303, 307, 310, 313, 315, 316, 323, 326, 329, 332, 334, 335, 337, 339, 343, 345, 346, 348, 351, 352, 354, 355, 360, 363, 364, 368, 371, 372, 374, 379, 381, 385, 386, 387, 389, 390, 392, 394, 395, 396, 397, 400, 401, 404, 407, 410, 411, 413, 417, 419, 421, 422, 423, 424, 425, 426, 427, 430, 431, 434, 436, 437, 438, 444, 445, 448, 450, 451, 453, 455, 458, 459, 462, 463, 467, 469, 470, 472, 473, 476, 477, 478, 479, 481, 482, 486, 488, 489, 491, 498, 499, 500, 503, 505, 506, 509, 510, 512, 516, 517, 519, 523, 524, 525, 526, 529, 537, 538, 539, 540, 541, 544, 547, 548, 549, 550, 552, 555, 559, 560, 561, 566, 570, 571, 576, 578, 581, 583, 584, 587, 591, 592, 594, 595, 596, 597, 598, 603, 605, 607, 609, 612, 613, 616, 618, 619, 621, 622, 625, 631, 632, 637, 638, 641, 644, 646, 648, 649, 650, 653, 656, 658, 659, 660, 662, 665, 666, 670, 674, 677, 678, 679, 680, 683, 686, 689, 690, 691, 693, 694, 709, 710, 713, 714, 716, 717, 719, 720, 721, 723, 726, 727, 728, 729, 731, 733, 735, 737, 738, 742, 744, 746, 748, 754, 755, 756, 757, 760, 762, 763, 766, 770, 771, 774, 775, 776, 777, 778, 779, 782, 783, 785, 786, 792, 793, 794, 799, 804, 805, 816, 817, 819, 822, 823, 828, 829, 830, 831, 833, 834, 835, 837, 838, 839, 840, 843, 848, 849, 850, 853, 854, 856, 857, 858, 859, 861, 862, 863, 864, 869, 877, 879, 883, 885, 889, 891, 892, 893, 895, 897, 900, 901, 902, 907, 909, 910, 912, 913, 916, 918, 919, 921, 924, 926, 927, 929, 931, 932, 933, 934, 938, 943, 951, 953, 957, 961, 963, 966, 967, 968, 969, 975, 976, 980, 982, 984, 985, 986, 988, 989, 990, 992, 993, 994, 998]
Portuguese : [2, 18, 26, 58, 97, 100, 106, 108, 144, 158, 187, 188, 232, 242, 269, 272, 297, 308, 312, 342, 359, 378, 382, 388, 393, 409, 415, 420, 447, 466, 474, 484, 487, 497, 518, 556, 562, 602, 608, 655, 671, 675, 698, 715, 751, 767, 772, 796, 836, 888, 908, 914, 936, 946, 947, 948, 959, 971, 977, 979, 981]
Spanish : [13, 14, 25, 43, 69, 103, 105, 129, 147, 160, 171, 180, 224, 260, 276, 304, 336, 349, 384, 405, 408, 414, 442, 452, 454, 460, 461, 492, 494, 501, 520, 568, 599, 606, 623, 624, 669, 685, 697, 701, 711, 725, 734, 747, 750, 752, 753, 773, 781, 797, 798, 809, 810, 812, 821, 825, 826, 841, 847, 866, 906, 911, 920, 935, 944, 952, 955, 995]
German : [15, 24, 57, 64, 72, 82, 146, 217, 227, 231, 241, 266, 284, 306, 327, 330, 353, 365, 435, 446, 471, 495, 508, 522, 533, 565, 585, 593, 614, 626, 630, 643, 687, 702, 704, 806, 807, 824, 832, 842, 846, 873, 878, 886, 899, 930, 941, 970, 983]
Korean : [17, 21, 28, 56, 101, 127, 139, 143, 157, 161, 185, 190, 198, 215, 219, 221, 223, 236, 256, 287, 317, 321, 322, 333, 344, 357, 362, 380, 391, 398, 403, 418, 429, 439, 457, 464, 490, 496, 507, 528, 530, 535, 536, 577, 580, 586, 601, 610, 617, 629, 654, 663, 664, 692, 700, 708, 722, 724, 732, 743, 764, 768, 784, 789, 791, 875, 896, 915, 923, 949, 954, 962, 965, 978, 991, 996, 997]
French : [30, 31, 34, 45, 59, 60, 84, 91, 107, 130, 132, 150, 159, 226, 253, 291, 305, 311, 314, 318, 331, 358, 375, 416, 456, 480, 493, 502, 521, 527, 553, 554, 557, 563, 574, 600, 628, 645, 651, 652, 661, 668, 673, 676, 688, 707, 739, 780, 788, 801, 803, 808, 844, 855, 894, 898, 903, 925, 928, 939, 942, 958, 964, 972, 987, 999]
Russian : [36, 39, 50, 53, 85, 88, 92, 98, 102, 109, 126, 141, 154, 164, 170, 195, 230, 249, 299, 319, 324, 325, 338, 340, 341, 356, 361, 370, 373, 399, 406, 432, 440, 441, 443, 465, 475, 483, 514, 515, 532, 545, 558, 564, 575, 588, 589, 634, 636, 639, 647, 682, 684, 695, 696, 699, 703, 718, 761, 790, 800, 811, 814, 827, 851, 852, 872, 874, 884, 887, 945, 956, 973, 974]
Japanese : [68, 78, 239, 282, 309, 542, 667, 845, 871, 890]
Chinese : [110, 120, 137, 145, 151, 193, 208, 247, 248, 252, 277, 347, 367, 369, 412, 428, 433, 504, 546, 615, 620, 705, 740, 741, 813, 815, 870, 876, 881, 940]
Czech : [116, 531, 534, 569, 820, 868]
Turkish : [121, 167, 176, 177, 199, 257, 376, 468, 485, 572, 635, 672, 681, 706, 730, 765, 802, 867, 882, 917, 950, 960]
Italian : [124, 156, 295, 350, 543, 579, 582, 604, 640, 657, 712, 736, 787, 795, 860, 904, 937]
Polish : [125, 173, 174, 200, 275, 328, 366, 567, 611, 745, 818, 905]
Thai : [191, 298, 320, 511, 627, 633, 642, 749, 758, 769, 865]
Arabic : [279, 402, 590, 759, 880]
Slovak : [377]
Other : [383]
Hungarian : [449, 573]
Greek : [513]
Finnish : [551]
Swedish : [922]

Из этих данных так же можно понять, что язык не является особо информативным признаком, у популярных языков стримеры, говорящие на них, распределены более-менее равномерно по всему топу, а стримеров, ведущих трансляции на менее популярных языках, слишком мало, данные по ним незначительны. Поэтому данный признак тоже удалим.

In [59]:
twitch_df = twitch_df.drop(['Language'], axis=1)

In [60]:
twitch_df

,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained
0,6196161750,215250,222720,27716,3246298,1734810,93036735
1,6091677300,211845,310998,25610,5310163,1370184,89705964
2,5644590915,515280,387315,10976,1767635,1023779,102611607
3,3970318140,517740,300575,7714,3944850,703986,106546942
4,3671000070,123660,285644,29602,8938903,2068424,78998587
...,...,...,...,...,...,...,...
995,122524635,13560,21359,9104,601927,562691,2162107
996,122523705,153000,3940,793,213212,52289,4399897
997,122452320,217410,6431,567,109068,-4942,3417970
998,122311065,104745,10543,1153,547446,109111,3926918
999,122192850,99180,13788,1205,178553,59432,2049420

Теперь, когда остались только нужные нам признаки, осталось экспортировать изменения в датафрейме.

In [61]:
#экспортируем изменения в датафрейме
twitch_df.to_csv('../data/twitch_data_preprocessed.csv', index=False)